// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static const String _defaultApiKey = 'AIzaSyCS-3zt1hQWDWSbISBd0kuUmAX2eJ5_e1w';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB', defaultValue: _defaultApiKey),
    appId: '1:658118593597:web:fc49d67175f2f39b44ae54',
    messagingSenderId: '658118593597',
    projectId: 'medibond-45fad',
    authDomain: 'medibond-45fad.firebaseapp.com',
    storageBucket: 'medibond-45fad.firebasestorage.app',
    measurementId: 'G-QMYJXZVJ5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_ANDROID', defaultValue: _defaultApiKey),
    appId: '1:658118593597:android:0f1ef9a897bdc52844ae54',
    messagingSenderId: '658118593597',
    projectId: 'medibond-45fad',
    storageBucket: 'medibond-45fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS', defaultValue: _defaultApiKey),
    appId: '1:658118593597:ios:0fa63da574d241f044ae54',
    messagingSenderId: '658118593597',
    projectId: 'medibond-45fad',
    storageBucket: 'medibond-45fad.firebasestorage.app',
    iosClientId:
        '658118593597-79iinf5gtfbt1ivlfatlk5g7epkorni9.apps.googleusercontent.com',
    iosBundleId: 'com.tenseitech.doctornect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_IOS', defaultValue: _defaultApiKey),
    appId: '1:658118593597:ios:0fa63da574d241f044ae54',
    messagingSenderId: '658118593597',
    projectId: 'medibond-45fad',
    storageBucket: 'medibond-45fad.firebasestorage.app',
    iosClientId:
        '658118593597-79iinf5gtfbt1ivlfatlk5g7epkorni9.apps.googleusercontent.com',
    iosBundleId: 'com.tenseitech.doctornect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB', defaultValue: _defaultApiKey),
    appId: '1:658118593597:web:fc49d67175f2f39b44ae54',
    messagingSenderId: '658118593597',
    projectId: 'medibond-45fad',
    authDomain: 'medibond-45fad.firebaseapp.com',
    storageBucket: 'medibond-45fad.firebasestorage.app',
    measurementId: 'G-QMYJXZVJ5Z',
  );
}
