// MediBond — Patient-Friendly Specialty Categories (30 home-screen cards)

const Map<String, List<String>> specialtyCategories = {
  'General Physician': [
    'General Physician',
    'General Medicine (Internal Medicine)',
    'Medicine (Internal)',
    'General Checkup',
    'Community Medicine',
    'Community Medicine Physician',
    'Community & Preventive Medicine',
    'Public Health Specialist',
    'Chronic Disease Management',
    'Occupational Health Physician',
    'Occupational Medicine Physician',
    'Rural Medicine Physician',
    'Radiologist',
    'Radiodiagnosis',
    'Diagnostics & Radiology',
    'CT & MRI Specialist',
    'CT & MRI Radiologist',
    'Breast Imaging Specialist',
    'Breast Imaging',
    'Ultrasound Specialist',
    'Ultrasound Radiologist',
    'Musculoskeletal Radiologist',
    'Musculoskeletal Radiology',
    'Neuroradiologist',
    'Neuroradiology',
    'Nuclear Medicine Specialist',
    'Nuclear Medicine',
    'Pathology & Lab Medicine',
    'Clinical Pathologist',
    'Clinical Pathology',
    'Anatomical Pathologist',
    'Anatomical Pathology',
    'Cytopathologist',
    'Cytopathology',
    'Hematopathologist',
    'Hematopathology',
    'Histopathologist',
    'Histopathology',
    'Immunopathologist',
    'Immunopathology',
    'Molecular Pathologist',
    'Molecular Pathology',
    'Forensic Pathologist',
    'Forensic Pathology',
    'Toxicologist',
    'Toxicology',
  ],
  "Women's Health": [
    'Gynecologist',
    'Obstetrics & Gynecology',
    'Obstetrics & Gynecology (OB-GYN)',
    'Adolescent Gynecologist',
    'Adolescent Gynecology',
    'Endoscopic Gynecologist',
    'Endoscopic Gynecology',
    'Laparoscopic Gynecologist',
    'Laparoscopic Gynecology',
    'Gynecologic Oncologist',
    'Gynecologic Oncology',
    'Maternal-Fetal Medicine Specialist',
    'Maternal-Fetal Medicine',
    'Menopause Specialist',
    'Menopause & HRT',
  ],
  'Child Care': [
    'Pediatrician',
    'Pediatrics',
    'General Pediatrics',
    'Developmental Pediatrician',
    'Developmental Pediatrics',
    'Neonatologist',
    'Neonatology',
    'Pediatric Cardiologist',
    'Pediatric Cardiology',
    'Pediatric Endocrinologist',
    'Pediatric Endocrinology',
    'Pediatric Gastroenterologist',
    'Pediatric Gastroenterology',
    'Pediatric Hematologist',
    'Pediatric Hematology',
    'Pediatric Infectious Disease Specialist',
    'Pediatric Infectious Diseases',
    'Pediatric Intensivist',
    'Pediatric Nephrologist',
    'Pediatric Nephrology',
    'Pediatric Neurologist',
    'Pediatric Neurology',
    'Pediatric Oncologist',
    'Pediatric Oncology',
    'Pediatric Pulmonologist',
    'Pediatric Pulmonology',
    'Pediatric Radiologist',
    'Pediatric Radiology',
    'Pediatric Rheumatologist',
    'Pediatric Rheumatology',
    'Pediatric Surgeon',
    'Pediatric Surgery',
  ],
  'Eye Specialist': [
    'Ophthalmologist',
    'Ophthalmology',
    'Cornea Specialist',
    'Cornea & External Disease',
    'Oculoplastic Surgeon',
    'Oculoplasty',
    'Vitreo-Retinal Surgeon',
    'Vitreo-Retinal Surgery',
    'Strabismus & Pediatric Ophthalmology',
    'Pediatric Ophthalmologist',
  ],
  'Ear, Nose & Throat': [
    'ENT Specialist',
    'ENT (Otolaryngology)',
    'Laryngologist',
    'Laryngology',
    'Rhinologist',
    'Rhinology',
    'Otoneurologist',
    'Otoneurology',
    'Audiologist',
    'Audiology',
    'Audiology Rehabilitation Specialist',
    'Audiology & Rehabilitation',
    'Skull Base Surgeon',
    'Skull Base Surgery',
    'Sensory & ENT',
  ],
  'Dentist': [
    'Dentist',
    'Dentistry',
    'General Dentistry',
    'Orthodontist',
    'Orthodontics',
    'Endodontist',
    'Endodontics',
    'Periodontist',
    'Periodontics',
    'Implantologist',
    'Implantology',
    'Oral Surgeon',
    'Oral Surgery',
    'Oral & Maxillofacial Surgeon',
    'Oral & Maxillofacial Surgery',
    'Oral Medicine Specialist',
    'Oral Medicine',
    'Oral Pathologist',
    'Oral Pathology',
    'Prosthodontist',
    'Prosthodontics',
    'Pedodontics (Pediatric Dentistry)',
    'Pediatric Dentist',
    'Public Health Dentist',
    'Public Health Dentistry',
  ],
  'Heart Specialist': [
    'Cardiologist',
    'Cardiology',
    'Cardiothoracic Surgeon',
    'Cardiothoracic Surgery',
    'Vascular Surgeon',
    'Vascular Surgery',
    'Interventional Radiologist',
    'Interventional Radiology',
  ],
  'Mental Wellness': [
    'Psychiatrist',
    'Psychiatry',
    'Addiction Psychiatrist',
    'Addiction Psychiatry',
    'Child Psychiatrist',
    'Child & Adolescent Psychiatry',
    'Geriatric Psychiatrist',
    'Geriatric Psychiatry',
    'Forensic Psychiatrist',
    'Forensic Psychiatry',
    'Liaison Psychiatrist',
    'Liaison Psychiatry',
    'Mental Health & Neurology',
  ],
  'Skin Specialist': [
    'Dermatologist',
    'Dermatology',
    'Aesthetic Dermatologist',
    'Aesthetic Dermatology',
    'Laser Dermatologist',
    'Laser Dermatology',
    'Trichologist',
    'Trichology',
    'Hair Transplant Surgeon',
    'Hair Transplant',
    'Skin, Hair & Aesthetics',
    'Leprologist',
    'Leprosy',
  ],
  'Bone & Joint': [
    'Orthopedic',
    'Orthopedic Surgeon',
    'Orthopedic Surgery',
    'Spine Surgeon',
    'Spine Surgery',
    'Hand Surgeon',
    'Hand Surgery',
    'Rheumatologist',
    'Rheumatology',
    'Sports Medicine Physician',
    'Sports Medicine',
    'Sports Rehabilitation Specialist',
    'Sports Rehabilitation',
    'Physical Medicine & Rehabilitation (PMR)',
    'PM&R Specialist',
  ],
  'Diabetes': [
    'Endocrinologist',
    'Endocrinology',
    'Metabolic Medicine Specialist',
    'Metabolic Medicine',
  ],
  'Stomach & Digestion': [
    'Gastroenterologist',
    'Gastroenterology',
    'Hepatologist',
    'Hepatology',
    'Colorectal Surgeon',
    'Colorectal Surgery',
    'Laparoscopic Surgeon',
    'Laparoscopic Surgery',
    'GI Oncologist',
    'Gastrointestinal Oncology',
  ],
  'Urinary Problems': [
    'Urogynecologist',
    'Urogynecology',
    'Nephrologist',
    'Nephrology',
    'Urologic Surgeon',
    'Urological Surgery',
    'Urologic Oncologist',
    'Urologic Oncology',
    'Kidney Transplant Surgeon',
    'Kidney Transplant Surgery',
  ],
  'Physiotherapist': [
    'Physiotherapist',
    'Physiotherapy',
    'Occupational Therapist',
    'Occupational Therapy',
    'Speech Therapist',
    'Speech & Language Pathology',
    'Prosthetics Specialist',
    'Prosthetics & Orthotics',
    'Rehabilitation & Allied',
  ],
  'Lung & Respiratory': [
    'Pulmonologist',
    'Pulmonology',
    'Sleep Medicine Specialist',
    'Sleep Medicine',
    'Thoracic Oncologist',
    'Thoracic Oncology',
  ],
  'Dietitian': [
    'Dietitian',
    'Nutrition & Dietetics',
  ],
  'Cancer Specialist': [
    'Medical Oncologist',
    'Medical Oncology',
    'Oncology',
    'Surgical Oncologist',
    'Surgical Oncology',
    'Radiation Oncologist',
    'Radiation Oncology',
    'Hemato-Oncologist',
    'Hemato-Oncology',
    'Head & Neck Oncologist',
    'Head & Neck Oncology',
  ],
  'Neurologist': [
    'Neurologist',
    'Neurology',
    'Neurosurgeon',
    'Neurosurgery',
    'Neuropsychiatrist',
    'Neuropsychiatry',
    'Epileptologist',
    'Epileptology',
    'Cognitive Neurologist',
    'Cognitive Neurology',
    'Movement Disorders Specialist',
    'Movement Disorders',
    'Neuro-Critical Care Specialist',
    'Neuro-Critical Care',
    'Neuro-Oncologist',
    'Neuro-Oncology',
  ],
  'General Surgeon': [
    'General Surgeon',
    'General Surgery',
    'Surgery',
    'Bariatric Surgeon',
    'Bariatric Surgery',
    'Burn Surgeon',
    'Burn Surgery',
    'Cosmetic Surgeon',
    'Cosmetic Surgery',
    'Plastic Surgeon',
    'Plastic & Reconstructive Surgery',
    'Robotic Surgeon',
    'Robotic Surgery',
    'Trauma Surgeon',
    'Trauma Surgery',
    'Trauma & Acute Care Surgery',
    'Acute Care Trauma Surgeon',
    'Liver Transplant Surgeon',
    'Liver Transplant Surgery',
  ],
  'Sexual Health': [
    'Venereologist',
    'Venereology (STIs)',
    'Reproductive Medicine & IVF',
    'IVF Specialist',
  ],
  'Ayurveda': [
    'Ayurvedic Doctor',
    'Ayurveda (BAMS)',
    'Panchkarma Specialist',
    'Panchkarma',
    'Naturopathy Specialist',
    'Naturopathy & Yoga',
    'Acupuncture Specialist',
    'Acupuncture',
    'Traditional & Integrative Medicine (AYUSH)',
    'Unani Doctor',
    'Unani Medicine (BUMS)',
    'Siddha Doctor',
    'Siddha Medicine',
  ],
  'Homeopathy': [
    'Homeopathic Doctor',
    'Homeopathy (BHMS)',
  ],
  'Veterinary': [
    'Veterinary Doctor',
    'Veterinary Surgeon',
    'Animal Health Specialist',
  ],
};

/// Returns the patient-friendly category name for [specialty], if listed.
String? getCategoryForSpecialty(String specialty) {
  for (final entry in specialtyCategories.entries) {
    if (entry.value.contains(specialty)) return entry.key;
  }
  return null;
}
