/// Maps patient-friendly speciality labels (UI) to exact Firestore / profile
/// strings from [AppConstants.specializationCategories].
abstract final class SpecialityMapper {
  SpecialityMapper._();

  /// UI label → backend department string (164 specialties).
  static const Map<String, String> uiToBackendSpecialityMap = {
    'Acupuncture Specialist': 'Acupuncture',
    'Acute Care Trauma Surgeon': 'Trauma & Acute Care Surgery',
    'Addiction Psychiatrist': 'Addiction Psychiatry',
    'Adolescent Gynecologist': 'Adolescent Gynecology',
    'Aesthetic Dermatologist': 'Aesthetic Dermatology',
    'Anatomical Pathologist': 'Anatomical Pathology',
    'Anesthesiologist': 'Anesthesiology',
    'Armed Forces Physician': 'Armed Forces Medicine',
    'Audiologist': 'Audiology',
    'Audiology Rehabilitation Specialist': 'Audiology & Rehabilitation',
    'Aviation Medicine Specialist': 'Aviation Medicine',
    'Ayurvedic Doctor': 'Ayurveda (BAMS)',
    'Bariatric Surgeon': 'Bariatric Surgery',
    'Biochemist (Medicine)': 'Biochemistry',
    'Breast Imaging Specialist': 'Breast Imaging',
    'Burn Surgeon': 'Burn Surgery',
    'CT & MRI Radiologist': 'CT & MRI Specialist',
    'Cardiologist': 'Cardiology',
    'Cardiothoracic Surgeon': 'Cardiothoracic Surgery',
    'Child Psychiatrist': 'Child & Adolescent Psychiatry',
    'Clinical Pathologist': 'Clinical Pathology',
    'Clinical Pharmacologist': 'Clinical Pharmacology',
    'Cognitive Neurologist': 'Cognitive Neurology',
    'Colorectal Surgeon': 'Colorectal Surgery',
    'Community Medicine Physician': 'Community Medicine',
    'Cornea Specialist': 'Cornea & External Disease',
    'Cosmetic Surgeon': 'Cosmetic Surgery',
    'Critical Care Physician': 'Critical Care Medicine',
    'Critical Care Specialist': 'Critical Care / ICU',
    'Cytopathologist': 'Cytopathology',
    'Dentist': 'General Dentistry',
    'Dermatologist': 'Dermatology',
    'Developmental Pediatrician': 'Developmental Pediatrics',
    'Dietitian': 'Nutrition & Dietetics',
    'Disaster Medicine Specialist': 'Pre-Hospital & Disaster Medicine',
    'ENT Specialist': 'ENT (Otolaryngology)',
    'Emergency Physician': 'Emergency Medicine',
    'Endocrinologist': 'Endocrinology',
    'Endodontist': 'Endodontics',
    'Endoscopic Gynecologist': 'Endoscopic Gynecology',
    'Epidemiologist': 'Epidemiology',
    'Epileptologist': 'Epileptology',
    'Forensic Pathologist': 'Forensic Pathology',
    'Forensic Psychiatrist': 'Forensic Psychiatry',
    'GI Oncologist': 'Gastrointestinal Oncology',
    'Gastroenterologist': 'Gastroenterology',
    'General Physician': 'General Medicine (Internal Medicine)',
    'General Surgeon': 'General Surgery',
    'Geriatric Psychiatrist': 'Geriatric Psychiatry',
    'Geriatrician': 'Geriatrics',
    'Gynecologic Oncologist': 'Gynecologic Oncology',
    'Gynecologist': 'Obstetrics & Gynecology (OB-GYN)',
    'Hair Transplant Surgeon': 'Hair Transplant',
    'Hand Surgeon': 'Hand Surgery',
    'Head & Neck Oncologist': 'Head & Neck Oncology',
    'Health Administrator': 'Health Administration',
    'Hemato-Oncologist': 'Hemato-Oncology',
    'Hematologist': 'Hematology',
    'Hematopathologist': 'Hematopathology',
    'Hepatologist': 'Hepatology',
    'Histopathologist': 'Histopathology',
    'Homeopathic Doctor': 'Homeopathy (BHMS)',
    'IVF Specialist': 'Reproductive Medicine & IVF',
    'Immunologist': 'Immunology',
    'Immunopathologist': 'Immunopathology',
    'Implantologist': 'Implantology',
    'Infectious Disease Specialist': 'Infectious Disease',
    'Interventional Radiologist': 'Interventional Radiology',
    'Kidney Transplant Surgeon': 'Kidney Transplant Surgery',
    'Laparoscopic Gynecologist': 'Laparoscopic Gynecology',
    'Laparoscopic Surgeon': 'Laparoscopic Surgery',
    'Laryngologist': 'Laryngology',
    'Laser Dermatologist': 'Laser Dermatology',
    'Leprologist': 'Leprosy',
    'Liaison Psychiatrist': 'Liaison Psychiatry',
    'Liver Transplant Surgeon': 'Liver Transplant Surgery',
    'Maternal-Fetal Medicine Specialist': 'Maternal-Fetal Medicine',
    'Medical Oncologist': 'Medical Oncology',
    'Menopause Specialist': 'Menopause & HRT',
    'Metabolic Medicine Specialist': 'Metabolic Medicine',
    'Microbiologist': 'Microbiology',
    'Molecular Pathologist': 'Molecular Pathology',
    'Movement Disorders Specialist': 'Movement Disorders',
    'Musculoskeletal Radiologist': 'Musculoskeletal Radiology',
    'Naturopathy Specialist': 'Naturopathy & Yoga',
    'Neonatologist': 'Neonatology',
    'Nephrologist': 'Nephrology',
    'Neuro-Critical Care Specialist': 'Neuro-Critical Care',
    'Neuro-Oncologist': 'Neuro-Oncology',
    'Neurologist': 'Neurology',
    'Neuropsychiatrist': 'Neuropsychiatry',
    'Neuroradiologist': 'Neuroradiology',
    'Neurosurgeon': 'Neurosurgery',
    'Nuclear Medicine Specialist': 'Nuclear Medicine',
    'Occupational Health Physician': 'Occupational Health',
    'Occupational Medicine Physician': 'Occupational Medicine',
    'Occupational Therapist': 'Occupational Therapy',
    'Oculoplastic Surgeon': 'Oculoplasty',
    'Ophthalmologist': 'Ophthalmology',
    'Oral & Maxillofacial Surgeon': 'Oral & Maxillofacial Surgery',
    'Oral Medicine Specialist': 'Oral Medicine',
    'Oral Pathologist': 'Oral Pathology',
    'Oral Surgeon': 'Oral Surgery',
    'Orthodontist': 'Orthodontics',
    'Orthopedic Surgeon': 'Orthopedic Surgery',
    'Otoneurologist': 'Otoneurology',
    'PM&R Specialist': 'Physical Medicine & Rehabilitation (PMR)',
    'Pain Management Specialist': 'Pain Management',
    'Palliative Care Physician': 'Palliative Medicine',
    'Palliative Care Specialist': 'Palliative Care',
    'Panchkarma Specialist': 'Panchkarma',
    'Pediatric Cardiologist': 'Pediatric Cardiology',
    'Pediatric Dentist': 'Pedodontics (Pediatric Dentistry)',
    'Pediatric Endocrinologist': 'Pediatric Endocrinology',
    'Pediatric Gastroenterologist': 'Pediatric Gastroenterology',
    'Pediatric Hematologist': 'Pediatric Hematology',
    'Pediatric Infectious Disease Specialist': 'Pediatric Infectious Diseases',
    'Pediatric Intensivist': 'Pediatric Intensivist',
    'Pediatric Nephrologist': 'Pediatric Nephrology',
    'Pediatric Neurologist': 'Pediatric Neurology',
    'Pediatric Oncologist': 'Pediatric Oncology',
    'Pediatric Ophthalmologist': 'Strabismus & Pediatric Ophthalmology',
    'Pediatric Pulmonologist': 'Pediatric Pulmonology',
    'Pediatric Radiologist': 'Pediatric Radiology',
    'Pediatric Rheumatologist': 'Pediatric Rheumatology',
    'Pediatric Surgeon': 'Pediatric Surgery',
    'Pediatrician': 'General Pediatrics',
    'Periodontist': 'Periodontics',
    'Physiotherapist': 'Physiotherapy',
    'Plastic Surgeon': 'Plastic & Reconstructive Surgery',
    'Prosthetics Specialist': 'Prosthetics & Orthotics',
    'Prosthodontist': 'Prosthodontics',
    'Psychiatrist': 'Psychiatry',
    'Public Health Dentist': 'Public Health Dentistry',
    'Public Health Specialist': 'Public Health',
    'Pulmonologist': 'Pulmonology',
    'Radiation Oncologist': 'Radiation Oncology',
    'Radiologist': 'Radiodiagnosis',
    'Rheumatologist': 'Rheumatology',
    'Rhinologist': 'Rhinology',
    'Robotic Surgeon': 'Robotic Surgery',
    'Rural Medicine Physician': 'Rural Medicine',
    'Siddha Doctor': 'Siddha Medicine',
    'Skull Base Surgeon': 'Skull Base Surgery',
    'Sleep Medicine Specialist': 'Sleep Medicine',
    'Speech Therapist': 'Speech & Language Pathology',
    'Spine Surgeon': 'Spine Surgery',
    'Sports Medicine Physician': 'Sports Medicine',
    'Sports Rehabilitation Specialist': 'Sports Rehabilitation',
    'Surgical Oncologist': 'Surgical Oncology',
    'Thoracic Oncologist': 'Thoracic Oncology',
    'Toxicologist': 'Toxicology',
    'Transfusion Medicine Specialist': 'Transfusion Medicine (Blood Banking)',
    'Trauma Surgeon': 'Trauma Surgery',
    'Trichologist': 'Trichology',
    'Ultrasound Radiologist': 'Ultrasound Specialist',
    'Unani Doctor': 'Unani Medicine (BUMS)',
    'Urogynecologist': 'Urogynecology',
    'Urologic Oncologist': 'Urologic Oncology',
    'Urologic Surgeon': 'Urological Surgery',
    'Vascular Surgeon': 'Vascular Surgery',
    'Venereologist': 'Venereology (STIs)',
    'Virologist': 'Virology',
    'Vitreo-Retinal Surgeon': 'Vitreo-Retinal Surgery',
  };

  /// All patient-facing speciality labels (sorted).
  static List<String> get patientSpecialityUiLabels {
    final keys = uiToBackendSpecialityMap.keys.toList();
    keys.sort();
    return keys;
  }

  /// Resolves a UI chip / shortcut label to the backend string for queries.
  static String toBackendSpeciality(String uiLabel) {
    final trimmed = uiLabel.trim();
    if (trimmed.isEmpty) return trimmed;
    return uiToBackendSpecialityMap[trimmed] ?? trimmed;
  }
}
